- name: Install MongoDB
  hosts: tag_MongoDB-Server  # Use the dynamic tag group
  become: yes
  tasks:
    - name: Add MongoDB Repository
      shell: |
        wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
        echo "deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
      args:
        warn: false

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Start and Enable MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes
